en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: 'Copyright &copy; {{< current_year >}} TWNW.info. This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/nc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">'
  title: "TWNW.info"
  params:
    description: "Wealth inequality and what you can do about it."
    ### accessibility ###
    accessibility:
      skip_text: "Skip to content"
      #help_text: "Accessibility Statement"
      #help_url: "/example-page/"
    ### calls to action ###
    main_cta:
      text: "Go To Gary's Economics"
      link: "https://wealtheconomics.org/"
    footer_cta:
      text: "Go To Gary's Economics"
      link: "https://wealtheconomics.org/"
    footer_cta_old:
      text: "Register To Vote"
      link: "https://www.gov.uk/register-to-vote"
    github_edit: "Edit this page on GitHub"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: "faq"
      name: "FAQs"
      url: "/faq/"
      weight: 3
#    - identifier: "blog"
#      name: "Blog"
#      url: "/blog/"
#      weight: 4
#es:
  # languageName: Spanish
  # contentDir: content/es
  # weight: 2
  # title: "Título del Sitio"
  # params:
  #   description: "Descripción del Sitio"
  # menu:
  #   main:
  #   - identifier: "about"
  #     name: "Acerca de"
  #     url: "/example-page/"
  #     weight: 1
  #   - identifier: "child-1"
  #     name: "Página Hija de Ejemplo"
  #     url: "/example-page/"
  #     weight: 1
  #     parent: "about"
  #   - identifier: "faq"
  #     name: "FAQs"
  #     url: "/faq/"
  #     weight: 3
  #   - identifier: "blog"
  #     name: "Blog"
  #     url: "/blog/"
  #     weight: 2
