######################## custom scripts & styles ####################

# Add custom assets relative to /static or via https
logo_on_white: "/img/twnw-icon.svg"
logo_on_black: "/img/twnw-icon-w.svg"
custom_js: []
custom_css: [https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css]

######################## custom config ####################

### default social share image (can also be set per lang) ###
images: ["/img/social-share.png"]

github:
  repo_url: "https://github.com/anjackson/twnw-website/blob/master"
  show_edit_link: true

social_links:
  devstats: ""
  discord: ""
  facebook: ""
  flickr: ""
  github: "https://github.com/anjackson/twnw-website"
  instagram: ""
  landscape: ""
  linkedin: ""
  mastodon: ""
  pinterest: ""
  rss: ""
  slack: ""
  stackoverflow: ""
  threads: ""
  twitter: ""
  x: ""
  youtube: ""

# Makes the header sticky on tall screens
sticky_header: true
# Enable search in header UI
show_search: false
